{% set name = "geomstats" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7a2eb36ba28690c43f47c5cf998756ef49db6f0c4fdb58d215903a825c474691

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - joblib >=0.14.1
    - matplotlib-base >=3.3.4
    - numpy >=1.18.1
    - pandas >=1.1.5
    - python >=3.7
    - scikit-learn >=0.22.1
    - scipy >=1.4.1

test:
  imports:
    - geomstats
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/geomstats/geomstats
  summary: 'Geometric statistics on manifolds'
  description: |
    Geomstats is an open-source Python package for computations and statistics on manifolds.
    The package is organized into two main modules: geometry and learning.
    The module geometry implements concepts in differential geometry, 
    and the module learning implements statistics and learning algorithms for data on manifolds.

  license: MIT
  license_family: MIT
  license_file: LICENSE.md

  doc_url: https://github.com/geomstats/geomstats
  dev_url: https://github.com/geomstats/geomstats

extra:
  recipe-maintainers:
    - ymontmarin
    - ninamiolane
    - nguigs
    - luisfpereira
