{% set name = "geomstats" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 20987f5b9fe5be1dfb5181b660e305c6357f68ef16b648af893112947ceeb6c7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - wheel
    - python >=3.9
  run:
    - joblib >=0.17.0
    - matplotlib-base >=3.3.4
    - numpy >=1.18.1
    - pandas >=1.1.5
    - python >=3.9
    - scikit-learn >=0.22.1
    - scipy >=1.9

test:
  imports:
    - geomstats
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/geomstats/geomstats
  summary: 'Geometric statistics on manifolds'
  description: |
    Geomstats is an open-source Python package for computations and statistics on manifolds.
    The package is organized into two main modules: geometry and learning.
    The module geometry implements concepts in differential geometry, 
    and the module learning implements statistics and learning algorithms for data on manifolds.

  license: MIT
  license_family: MIT
  license_file: LICENSE.md

  doc_url: https://github.com/geomstats/geomstats
  dev_url: https://github.com/geomstats/geomstats

extra:
  recipe-maintainers:
    - ymontmarin
    - ninamiolane
    - nguigs
    - luisfpereira
